Creating catch_all_lambda configuration
NHSDigital/immunisation-fhir-api pull request #38
Opened 2023-10-08 23:55 UTC by ewan-IW

## Summary
* Routine Change
* :exclamation: Breaking Change
* :robot: Operational or Infrastructure Change
* :sparkles: New Feature
* :warning: Potential issues that might be caused by this change

Add any other relevant notes or explanations here. **Remove this line if you have nothing to add.**

## Reviews Required
* [x] Dev
* [ ] Test
* [ ] Tech Author
* [ ] Product Owner

## Review Checklist
:information_source: This section is to be filled in by the **reviewer**.

* [ ] I have reviewed the changes in this PR and they fill all or part of the acceptance criteria of the ticket, and the code is in a mergeable state.
* [ ] If there were infrastructure, operational, or build changes, I have made sure there is sufficient evidence that the changes will work.
* [ ] I have ensured the changelog has been updated by the submitter, if necessary.

2023-10-11 18:37 UTC, artronics requested changes

2023-10-11 18:37 UTC, artronics commented on terraform/catch_all_lambda/catch_all_lambda.tf
> +output "catch_all_lambda_zip_name" {
Apart from function name, do you need the rest of these outputs? This module should take care of deployment and function name should be the only thing being exposed to the outside.

2023-10-12 10:48 UTC, ewan-IW commented on proxies/live/apiproxy/proxies/default.xml
>    </RouteRule>
I've removed the catch-all target

2023-10-12 11:04 UTC, ewan-IW commented on terraform/api_gateway/api.tf
> +data "aws_lambda_function" "catch_all_lambda" {
Removed the data!

2023-10-17 12:24 UTC, artronics approved these changes

2023-10-18 08:44 UTC, merged